using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Configuration;
using System.Data.Common;
using System.Data.Odbc;
using System.Data.OleDb;
using Ede.Uof.Utility.Data;
using Ede.Uof.WKF.ExternalUtility;
using System.Xml;
using System.Xml.Linq;

namespace TKUOF.TRIGGER.COPMA
{
    class EndFormTrigger : ICallbackTriggerPlugin
    {
        public class DATACOPMA
        {
            public string COMPANY;
            public string CREATOR;
            public string USR_GROUP;
            public string CREATE_DATE;
            public string MODIFIER;
            public string MODI_DATE;
            public string FLAG;
            public string CREATE_TIME;
            public string MODI_TIME;
            public string TRANS_TYPE;
            public string TRANS_NAME;
            public string sync_date;
            public string sync_time;
            public string sync_count;
            public string sync_mark;
            public string DataGroup;
            public string DataUser;          

            public string MA001;
            public string MA002;
            public string MA003;
            public string MA004;
            public string MA005;
            public string MA006;
            public string MA007;
            public string MA008;
            public string MA009;
            public string MA010;
            public string MA011;
            public string MA012;
            public string MA013;
            public string MA014;
            public string MA015;
            public string MA016;
            public string MA017;
            public string MA018;
            public string MA019;
            public string MA020;
            public string MA021;
            public string MA022;
            public string MA023;
            public string MA024;
            public string MA025;
            public string MA026;
            public string MA027;
            public string MA028;
            public string MA029;
            public string MA030;
            public string MA031;
            public string MA032;
            public string MA033;
            public string MA034;
            public string MA035;
            public string MA036;
            public string MA037;
            public string MA038;
            public string MA039;
            public string MA040;
            public string MA041;
            public string MA042;
            public string MA043;
            public string MA044;
            public string MA045;
            public string MA046;
            public string MA047;
            public string MA048;
            public string MA049;
            public string MA050;
            public string MA051;
            public string MA052;
            public string MA053;
            public string MA054;
            public string MA055;
            public string MA056;
            public string MA057;
            public string MA058;
            public string MA059;
            public string MA060;
            public string MA061;
            public string MA062;
            public string MA063;
            public string MA064;
            public string MA065;
            public string MA066;
            public string MA067;
            public string MA068;
            public string MA069;
            public string MA070;
            public string MA071;
            public string MA072;
            public string MA073;
            public string MA074;
            public string MA075;
            public string MA076;
            public string MA077;
            public string MA078;
            public string MA079;
            public string MA080;
            public string MA081;
            public string MA082;
            public string MA083;
            public string MA084;
            public string MA085;
            public string MA086;
            public string MA087;
            public string MA088;
            public string MA089;
            public string MA090;
            public string MA091;
            public string MA092;
            public string MA093;
            public string MA094;
            public string MA095;
            public string MA096;
            public string MA097;
            public string MA098;
            public string MA099;
            public string MA100;
            public string MA101;
            public string MA102;
            public string MA103;
            public string MA104;
            public string MA105;
            public string MA106;
            public string MA107;
            public string MA108;
            public string MA109;
            public string MA110;
            public string MA111;
            public string MA112;
            public string MA113;
            public string MA114;
            public string MA115;
            public string MA116;
            public string MA117;
            public string MA118;
            public string MA119;
            public string MA120;
            public string MA121;
            public string MA122;
            public string MA123;
            public string MA124;
            public string MA125;
            public string MA126;
            public string MA127;
            public string MA128;
            public string MA129;
            public string MA130;
            public string MA131;
            public string MA132;
            public string MA133;
            public string MA134;
            public string MA135;
            public string MA136;
            public string MA137;
            public string MA138;
            public string MA139;
            public string MA140;
            public string MA141;
            public string MA142;
            public string MA143;
            public string MA144;
            public string MA145;
            public string MA146;
            public string MA147;
            public string MA148;
            public string MA149;
            public string MA150;
            public string MA151;
            public string MA152;
            public string MA153;
            public string MA154;
            public string MA155;
            public string MA156;
            public string MA157;
            public string MA158;
            public string MA159;
            public string MA160;
            public string MA161;
            public string MA162;
            public string MA163;
            public string UDF01;
            public string UDF02;
            public string UDF03;
            public string UDF04;
            public string UDF05;
            public string UDF06;
            public string UDF07;
            public string UDF08;
            public string UDF09;
            public string UDF10;

        }
        public void Finally()
        {
            
        }

        public string GetFormResult(ApplyTask applyTask)
        {
            DATACOPMA COPMA = new DATACOPMA();

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.LoadXml(applyTask.CurrentDocXML);
  
            //MA001 = applyTask.Task.CurrentDocument.Fields["MA001"].FieldValue.ToString().Trim();
            //MA002 = applyTask.Task.CurrentDocument.Fields["MA002"].FieldValue.ToString().Trim();

            XmlNode node= xmlDoc.SelectSingleNode("./Form/FormFieldValue/FieldItem/FieldValue");

            COPMA.COMPANY= "TK";
            COPMA.CREATOR = node.Attributes["MA016"].Value;
            COPMA.USR_GROUP = "106000";
            COPMA.CREATE_DATE = DateTime.Now.ToString("yyyyMMdd");
            COPMA.MODIFIER = "";
            COPMA.MODI_DATE = DateTime.Now.ToString("yyyyMMdd");
            COPMA.FLAG = "1";
            COPMA.CREATE_TIME = DateTime.Now.ToString("HH:mm:ss");
            COPMA.MODI_TIME = DateTime.Now.ToString("HH:mm:ss");
            COPMA.TRANS_TYPE = "P001";
            COPMA.TRANS_NAME = "COPI01";
            COPMA.sync_date = "";
            COPMA.sync_time = "";
            COPMA.sync_count = "0";
            COPMA.sync_mark = "";
            COPMA.DataUser = "";
            COPMA.DataGroup = "106000";        
            COPMA.MA001 = node.Attributes["MA001"].Value;
            COPMA.MA002 = node.Attributes["MA002"].Value;
            COPMA.MA003 = node.Attributes["MA003"].Value;
            COPMA.MA004 = node.Attributes["MA004"].Value;
            COPMA.MA005 = node.Attributes["MA005"].Value;
            COPMA.MA006 = node.Attributes["MA006"].Value;
            COPMA.MA007 = "";
            COPMA.MA008 = node.Attributes["MA008"].Value;
            COPMA.MA009 = node.Attributes["MA009"].Value;
            COPMA.MA010 = node.Attributes["MA010"].Value;
            COPMA.MA011 = node.Attributes["MA011"].Value;
            COPMA.MA012 = node.Attributes["MA012"].Value;
            COPMA.MA013 = node.Attributes["MA013"].Value;
            COPMA.MA014 = node.Attributes["MA014"].Value;
            COPMA.MA015 = node.Attributes["MA015"].Value;
            COPMA.MA016 = node.Attributes["MA016"].Value;
            COPMA.MA017 = node.Attributes["MA017"].Value;
            COPMA.MA018 = node.Attributes["MA018"].Value;
            COPMA.MA019 = node.Attributes["MA019"].Value;
            COPMA.MA020 = "";
            COPMA.MA021 = "";
            COPMA.MA022 = "";
            COPMA.MA023 = node.Attributes["MA023"].Value;
            COPMA.MA024 = "";
            COPMA.MA025 = node.Attributes["MA025"].Value;
            COPMA.MA026 = "";
            COPMA.MA027 = node.Attributes["MA027"].Value;
            COPMA.MA028 = node.Attributes["MA028"].Value;
            COPMA.MA029 = "";
            COPMA.MA030 = "";
            COPMA.MA031 = node.Attributes["MA031"].Value;
            COPMA.MA032 = node.Attributes["MA032"].Value;
            COPMA.MA033 = node.Attributes["MA033"].Value;
            COPMA.MA034 = node.Attributes["MA034"].Value;
            COPMA.MA035 = node.Attributes["MA035"].Value;
            COPMA.MA036 = node.Attributes["MA036"].Value;
            COPMA.MA037 = node.Attributes["MA037"].Value;
            COPMA.MA038 = node.Attributes["MA038"].Value;
            COPMA.MA039 = node.Attributes["MA039"].Value;
            COPMA.MA040 = node.Attributes["MA040"].Value;
            COPMA.MA041 = node.Attributes["MA041"].Value;
            COPMA.MA042 = node.Attributes["MA042"].Value;
            COPMA.MA043 = node.Attributes["MA043"].Value;
            COPMA.MA044 = node.Attributes["MA044"].Value;
            COPMA.MA045 = node.Attributes["MA045"].Value;
            COPMA.MA046 = node.Attributes["MA046"].Value;
            COPMA.MA047 = node.Attributes["MA047"].Value;
            COPMA.MA048 = node.Attributes["MA048"].Value;
            COPMA.MA049 = node.Attributes["MA049"].Value;
            COPMA.MA050 = "";
            COPMA.MA051 = "";
            COPMA.MA052 = "";
            COPMA.MA053 = "";
            COPMA.MA054 = "";
            COPMA.MA055 = "";
            COPMA.MA056 = "";
            COPMA.MA057 = "";
            COPMA.MA058 = "";
            COPMA.MA059 = node.Attributes["MA059"].Value;
            COPMA.MA060 = node.Attributes["MA060"].Value;
            COPMA.MA061 = node.Attributes["MA061"].Value;
            COPMA.MA062 = "";
            COPMA.MA063 = "";
            COPMA.MA064 = "";
            COPMA.MA065 = "";
            COPMA.MA066 = node.Attributes["MA066"].Value;
            COPMA.MA067 = "0";
            COPMA.MA068 = "";
            COPMA.MA069 = "";
            COPMA.MA070 = "";
            COPMA.MA071 = node.Attributes["MA071"].Value;
            COPMA.MA072 = "";
            COPMA.MA073 = "";
            COPMA.MA074 = "";
            COPMA.MA075 = node.Attributes["MA075"].Value;
            COPMA.MA076 = node.Attributes["MA076"].Value;
            COPMA.MA077 = "";
            COPMA.MA078 = "";
            COPMA.MA079 = "";
            COPMA.MA080 = "";
            COPMA.MA081 = "";
            COPMA.MA082 = "";
            COPMA.MA083 = node.Attributes["MA083"].Value;
            COPMA.MA084 = node.Attributes["MA084"].Value;
            COPMA.MA085 = node.Attributes["MA085"].Value;
            COPMA.MA086 = node.Attributes["MA086"].Value;
            COPMA.MA087 = node.Attributes["MA087"].Value;
            COPMA.MA088 = node.Attributes["MA088"].Value;
            COPMA.MA089 = node.Attributes["MA089"].Value;
            COPMA.MA090 = node.Attributes["MA090"].Value;
            COPMA.MA091 = node.Attributes["MA091"].Value;
            COPMA.MA092 = node.Attributes["MA092"].Value;
            COPMA.MA093 = node.Attributes["MA093"].Value;
            COPMA.MA094 = node.Attributes["MA094"].Value;
            COPMA.MA095 = node.Attributes["MA095"].Value;
            COPMA.MA096 = node.Attributes["MA096"].Value;
            COPMA.MA097 = node.Attributes["MA097"].Value;
            COPMA.MA098 = node.Attributes["MA098"].Value;
            COPMA.MA099 = node.Attributes["MA099"].Value;
            COPMA.MA100 = node.Attributes["MA100"].Value;
            COPMA.MA101 = node.Attributes["MA101"].Value;
            COPMA.MA102 = node.Attributes["MA102"].Value;
            COPMA.MA103 = node.Attributes["MA103"].Value;
            COPMA.MA104 = "";
            COPMA.MA105 = "";
            COPMA.MA106 = node.Attributes["MA015"].Value;
            COPMA.MA107 = "";
            COPMA.MA108 = "";
            COPMA.MA109 = "";
            COPMA.MA110 = "";
            COPMA.MA111 = "";
            COPMA.MA112 = "";
            COPMA.MA113 = "0";
            COPMA.MA114 = "0";
            COPMA.MA115 = "";
            COPMA.MA116 = "";
            COPMA.MA117 = "";
            COPMA.MA118 = "";
            COPMA.MA119 = "";
            COPMA.MA120 = "";
            COPMA.MA121 = "";
            COPMA.MA122 = "";
            COPMA.MA123 = "";
            COPMA.MA124 = "";
            COPMA.MA125 = "0";
            COPMA.MA126 = "0";
            COPMA.MA127 = node.Attributes["MA127"].Value;
            COPMA.MA128 = "";
            COPMA.MA129 = "";
            COPMA.MA130 = ""; 
            COPMA.MA131 = "";
            COPMA.MA132 = node.Attributes["MA132"].Value;
            COPMA.MA133 = node.Attributes["MA133"].Value;
            COPMA.MA134 = "";
            COPMA.MA135 = "";
            COPMA.MA136 = "";
            COPMA.MA137 = "";
            COPMA.MA138 = "0";
            COPMA.MA139 = "";
            COPMA.MA140 = "";
            COPMA.MA141 = "0";
            COPMA.MA142 = "";
            COPMA.MA143 = "";
            COPMA.MA144 = "";
            COPMA.MA145 = "0";
            COPMA.MA146 = "";
            COPMA.MA147 = node.Attributes["MA147"].Value;
            COPMA.MA148 = node.Attributes["MA148"].Value;
            COPMA.MA149 = node.Attributes["MA149"].Value;
            COPMA.MA150 = node.Attributes["MA150"].Value;
            COPMA.MA151 = "0";
            COPMA.MA152 = "0";
            COPMA.MA153 = "0";
            COPMA.MA154 = "0";
            COPMA.MA155 = "";
            COPMA.MA156 = "";
            COPMA.MA157 = "";
            COPMA.MA158 = "";
            COPMA.MA159 = "";
            COPMA.MA160 = "";
            COPMA.MA161 = "Y";
            COPMA.MA162 = node.Attributes["MA162"].Value;
            COPMA.MA163 = "";
            COPMA.UDF01 = "";
            COPMA.UDF02 = node.Attributes["UDF02"].Value;
            COPMA.UDF03 = "";
            COPMA.UDF04 = "";
            COPMA.UDF05 = "";
            COPMA.UDF06 = "0";
            COPMA.UDF07 = "0";
            COPMA.UDF08 = "0";
            COPMA.UDF09 = "0";
            COPMA.UDF10 = "0";

            if (applyTask.FormResult == Ede.Uof.WKF.Engine.ApplyResult.Adopt)
            {
                if (!string.IsNullOrEmpty(COPMA.MA001) && !string.IsNullOrEmpty(COPMA.MA002))
                {                   
                    ADDTKCOPMA(COPMA);
                }
            }

            return "";
        }

        public void OnError(Exception errorException)
        {
            
        }

        public void ADDTKCOPMA(DATACOPMA COPMA)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["ERPconnectionstring"].ToString();

            StringBuilder queryString = new StringBuilder();
            //queryString.AppendFormat(@" INSERT INTO [TK].dbo.COPMA");
            //queryString.AppendFormat(@" (COMPANY,MA001,MA002)");
            //queryString.AppendFormat(@" VALUES (@MA001,@MA001,@MA002)");

            queryString.AppendFormat(@" INSERT INTO [TK].dbo.COPMA");
            queryString.AppendFormat(@" (");
            queryString.AppendFormat(@" [COMPANY],[CREATOR],[USR_GROUP],[CREATE_DATE],[MODIFIER],[MODI_DATE],[FLAG],[CREATE_TIME],[MODI_TIME],[TRANS_TYPE]");
            queryString.AppendFormat(@" ,[TRANS_NAME],[sync_date],[sync_time],[sync_mark],[sync_count],[DataUser],[DataGroup]");
            queryString.AppendFormat(@" ,[MA001],[MA002],[MA003],[MA004],[MA005],[MA006],[MA007],[MA008],[MA009],[MA010]");
            queryString.AppendFormat(@" ,[MA011],[MA012],[MA013],[MA014],[MA015],[MA016],[MA017],[MA018],[MA019],[MA020]");
            queryString.AppendFormat(@" ,[MA021],[MA022],[MA023],[MA024],[MA025],[MA026],[MA027],[MA028],[MA029],[MA030]");
            queryString.AppendFormat(@" ,[MA031],[MA032],[MA033],[MA034],[MA035],[MA036],[MA037],[MA038],[MA039],[MA040]");
            queryString.AppendFormat(@" ,[MA041],[MA042],[MA043],[MA044],[MA045],[MA046],[MA047],[MA048],[MA049],[MA050]");
            queryString.AppendFormat(@" ,[MA051],[MA052],[MA053],[MA054],[MA055],[MA056],[MA057],[MA058],[MA059],[MA060]");
            queryString.AppendFormat(@" ,[MA061],[MA062],[MA063],[MA064],[MA065],[MA066],[MA067],[MA068],[MA069],[MA070]");
            queryString.AppendFormat(@" ,[MA071],[MA072],[MA073],[MA074],[MA075],[MA076],[MA077],[MA078],[MA079],[MA080]");
            queryString.AppendFormat(@" ,[MA081],[MA082],[MA083],[MA084],[MA085],[MA086],[MA087],[MA088],[MA089],[MA090]");
            queryString.AppendFormat(@" ,[MA091],[MA092],[MA093],[MA094],[MA095],[MA096],[MA097],[MA098],[MA099],[MA100]");
            queryString.AppendFormat(@" ,[MA101],[MA102],[MA103],[MA104],[MA105],[MA106],[MA107],[MA108],[MA109],[MA110]");
            queryString.AppendFormat(@" ,[MA111],[MA112],[MA113],[MA114],[MA115],[MA116],[MA117],[MA118],[MA119],[MA120]");
            queryString.AppendFormat(@" ,[MA121],[MA122],[MA123],[MA124],[MA125],[MA126],[MA127],[MA128],[MA129],[MA130]");
            queryString.AppendFormat(@" ,[MA131],[MA132],[MA133],[MA134],[MA135],[MA136],[MA137],[MA138],[MA139],[MA140]");
            queryString.AppendFormat(@" ,[MA141],[MA142],[MA143],[MA144],[MA145],[MA146],[MA147],[MA148],[MA149],[MA150]");
            queryString.AppendFormat(@" ,[MA151],[MA152],[MA153],[MA154],[MA155],[MA156],[MA157],[MA158],[MA159],[MA160]");
            queryString.AppendFormat(@" ,[MA161],[MA162],[MA163]");
            queryString.AppendFormat(@" ,[UDF01],[UDF02],[UDF03],[UDF04],[UDF05],[UDF06],[UDF07],[UDF08],[UDF09],[UDF10]");
            queryString.AppendFormat(@" )");
            queryString.AppendFormat(@" VALUES");
            queryString.AppendFormat(@" (");
            queryString.AppendFormat(@" @COMPANY,@CREATOR,@USR_GROUP,@CREATE_DATE,@MODIFIER,@MODI_DATE,@FLAG,@CREATE_TIME,@MODI_TIME,@TRANS_TYPE");
            queryString.AppendFormat(@" ,@TRANS_NAME,@sync_date,@sync_time,@sync_mark,@sync_count,@DataUser,@DataGroup");
            queryString.AppendFormat(@" ,@MA001,@MA002,@MA003,@MA004,@MA005,@MA006,@MA007,@MA008,@MA009,@MA010");
            queryString.AppendFormat(@" ,@MA011,@MA012,@MA013,@MA014,@MA015,@MA016,@MA017,@MA018,@MA019,@MA020");
            queryString.AppendFormat(@" ,@MA021,@MA022,@MA023,@MA024,@MA025,@MA026,@MA027,@MA028,@MA029,@MA030");
            queryString.AppendFormat(@" ,@MA031,@MA032,@MA033,@MA034,@MA035,@MA036,@MA037,@MA038,@MA039,@MA040");
            queryString.AppendFormat(@" ,@MA041,@MA042,@MA043,@MA044,@MA045,@MA046,@MA047,@MA048,@MA049,@MA050");
            queryString.AppendFormat(@" ,@MA051,@MA052,@MA053,@MA054,@MA055,@MA056,@MA057,@MA058,@MA059,@MA060");
            queryString.AppendFormat(@" ,@MA061,@MA062,@MA063,@MA064,@MA065,@MA066,@MA067,@MA068,@MA069,@MA070");
            queryString.AppendFormat(@" ,@MA071,@MA072,@MA073,@MA074,@MA075,@MA076,@MA077,@MA078,@MA079,@MA080");
            queryString.AppendFormat(@" ,@MA081,@MA082,@MA083,@MA084,@MA085,@MA086,@MA087,@MA088,@MA089,@MA090");
            queryString.AppendFormat(@" ,@MA091,@MA092,@MA093,@MA094,@MA095,@MA096,@MA097,@MA098,@MA099,@MA100");
            queryString.AppendFormat(@" ,@MA101,@MA102,@MA103,@MA104,@MA105,@MA106,@MA107,@MA108,@MA109,@MA110");
            queryString.AppendFormat(@" ,@MA111,@MA112,@MA113,@MA114,@MA115,@MA116,@MA117,@MA118,@MA119,@MA120");
            queryString.AppendFormat(@" ,@MA121,@MA122,@MA123,@MA124,@MA125,@MA126,@MA127,@MA128,@MA129,@MA130");
            queryString.AppendFormat(@" ,@MA131,@MA132,@MA133,@MA134,@MA135,@MA136,@MA137,@MA138,@MA139,@MA140");
            queryString.AppendFormat(@" ,@MA141,@MA142,@MA143,@MA144,@MA145,@MA146,@MA147,@MA148,@MA149,@MA150");
            queryString.AppendFormat(@" ,@MA151,@MA152,@MA153,@MA154,@MA155,@MA156,@MA157,@MA158,@MA159,@MA160");
            queryString.AppendFormat(@" ,@MA161,@MA162,@MA163");
            queryString.AppendFormat(@" ,@UDF01,@UDF02,@UDF03,@UDF04,@UDF05,@UDF06,@UDF07,@UDF08,@UDF09,@UDF10");
            queryString.AppendFormat(@" )");            
            queryString.AppendFormat(@" ");
            queryString.AppendFormat(@" ");

            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {

                    SqlCommand command = new SqlCommand(queryString.ToString(), connection);
                    command.Parameters.Add("@COMPANY", SqlDbType.NVarChar).Value = COPMA.COMPANY;
                    command.Parameters.Add("@CREATOR", SqlDbType.NVarChar).Value = COPMA.CREATOR;
                    command.Parameters.Add("@USR_GROUP", SqlDbType.NVarChar).Value = COPMA.USR_GROUP;
                    command.Parameters.Add("@CREATE_DATE", SqlDbType.NVarChar).Value = COPMA.CREATE_DATE;
                    command.Parameters.Add("@MODIFIER", SqlDbType.NVarChar).Value = COPMA.MODIFIER;
                    command.Parameters.Add("@MODI_DATE", SqlDbType.NVarChar).Value = COPMA.MODI_DATE;
                    command.Parameters.Add("@FLAG", SqlDbType.NVarChar).Value = COPMA.FLAG;
                    command.Parameters.Add("@CREATE_TIME", SqlDbType.NVarChar).Value = COPMA.CREATE_TIME;
                    command.Parameters.Add("@MODI_TIME", SqlDbType.NVarChar).Value = COPMA.MODI_TIME;
                    command.Parameters.Add("@TRANS_TYPE", SqlDbType.NVarChar).Value = COPMA.TRANS_TYPE;
                    command.Parameters.Add("@TRANS_NAME", SqlDbType.NVarChar).Value = COPMA.TRANS_NAME;
                    command.Parameters.Add("@sync_date", SqlDbType.NVarChar).Value = COPMA.sync_date;
                    command.Parameters.Add("@sync_time", SqlDbType.NVarChar).Value = COPMA.sync_time;
                    command.Parameters.Add("@sync_mark", SqlDbType.NVarChar).Value = COPMA.sync_mark;
                    command.Parameters.Add("@sync_count", SqlDbType.NVarChar).Value = COPMA.sync_count;
                    command.Parameters.Add("@DataUser", SqlDbType.NVarChar).Value = COPMA.DataUser;
                    command.Parameters.Add("@DataGroup", SqlDbType.NVarChar).Value = COPMA.DataGroup;
                    command.Parameters.Add("@MA001", SqlDbType.NVarChar).Value = COPMA.MA001;
                    command.Parameters.Add("@MA002", SqlDbType.NVarChar).Value = COPMA.MA002;
                    command.Parameters.Add("@MA003", SqlDbType.NVarChar).Value = COPMA.MA003;
                    command.Parameters.Add("@MA004", SqlDbType.NVarChar).Value = COPMA.MA004;
                    command.Parameters.Add("@MA005", SqlDbType.NVarChar).Value = COPMA.MA005;
                    command.Parameters.Add("@MA006", SqlDbType.NVarChar).Value = COPMA.MA006;
                    command.Parameters.Add("@MA007", SqlDbType.NVarChar).Value = COPMA.MA007;
                    command.Parameters.Add("@MA008", SqlDbType.NVarChar).Value = COPMA.MA008;
                    command.Parameters.Add("@MA009", SqlDbType.NVarChar).Value = COPMA.MA009;
                    command.Parameters.Add("@MA010", SqlDbType.NVarChar).Value = COPMA.MA010;
                    command.Parameters.Add("@MA011", SqlDbType.NVarChar).Value = COPMA.MA011;
                    command.Parameters.Add("@MA012", SqlDbType.NVarChar).Value = COPMA.MA012;
                    command.Parameters.Add("@MA013", SqlDbType.NVarChar).Value = COPMA.MA013;
                    command.Parameters.Add("@MA014", SqlDbType.NVarChar).Value = COPMA.MA014;
                    command.Parameters.Add("@MA015", SqlDbType.NVarChar).Value = COPMA.MA015;
                    command.Parameters.Add("@MA016", SqlDbType.NVarChar).Value = COPMA.MA016;
                    command.Parameters.Add("@MA017", SqlDbType.NVarChar).Value = COPMA.MA017;
                    command.Parameters.Add("@MA018", SqlDbType.NVarChar).Value = COPMA.MA018;
                    command.Parameters.Add("@MA019", SqlDbType.NVarChar).Value = COPMA.MA019;
                    command.Parameters.Add("@MA020", SqlDbType.NVarChar).Value = COPMA.MA020;
                    command.Parameters.Add("@MA021", SqlDbType.NVarChar).Value = COPMA.MA021;
                    command.Parameters.Add("@MA022", SqlDbType.NVarChar).Value = COPMA.MA022;
                    command.Parameters.Add("@MA023", SqlDbType.NVarChar).Value = COPMA.MA023;
                    command.Parameters.Add("@MA024", SqlDbType.NVarChar).Value = COPMA.MA024;
                    command.Parameters.Add("@MA025", SqlDbType.NVarChar).Value = COPMA.MA025;
                    command.Parameters.Add("@MA026", SqlDbType.NVarChar).Value = COPMA.MA026;
                    command.Parameters.Add("@MA027", SqlDbType.NVarChar).Value = COPMA.MA027;
                    command.Parameters.Add("@MA028", SqlDbType.NVarChar).Value = COPMA.MA028;
                    command.Parameters.Add("@MA029", SqlDbType.NVarChar).Value = COPMA.MA029;
                    command.Parameters.Add("@MA030", SqlDbType.NVarChar).Value = COPMA.MA030;
                    command.Parameters.Add("@MA031", SqlDbType.NVarChar).Value = COPMA.MA031;
                    command.Parameters.Add("@MA032", SqlDbType.NVarChar).Value = COPMA.MA032;
                    command.Parameters.Add("@MA033", SqlDbType.NVarChar).Value = COPMA.MA033;
                    command.Parameters.Add("@MA034", SqlDbType.NVarChar).Value = COPMA.MA034;
                    command.Parameters.Add("@MA035", SqlDbType.NVarChar).Value = COPMA.MA035;
                    command.Parameters.Add("@MA036", SqlDbType.NVarChar).Value = COPMA.MA036;
                    command.Parameters.Add("@MA037", SqlDbType.NVarChar).Value = COPMA.MA037;
                    command.Parameters.Add("@MA038", SqlDbType.NVarChar).Value = COPMA.MA038;
                    command.Parameters.Add("@MA039", SqlDbType.NVarChar).Value = COPMA.MA039;
                    command.Parameters.Add("@MA040", SqlDbType.NVarChar).Value = COPMA.MA040;
                    command.Parameters.Add("@MA041", SqlDbType.NVarChar).Value = COPMA.MA041;
                    command.Parameters.Add("@MA042", SqlDbType.NVarChar).Value = COPMA.MA042;
                    command.Parameters.Add("@MA043", SqlDbType.NVarChar).Value = COPMA.MA043;
                    command.Parameters.Add("@MA044", SqlDbType.NVarChar).Value = COPMA.MA044;
                    command.Parameters.Add("@MA045", SqlDbType.NVarChar).Value = COPMA.MA045;
                    command.Parameters.Add("@MA046", SqlDbType.NVarChar).Value = COPMA.MA046;
                    command.Parameters.Add("@MA047", SqlDbType.NVarChar).Value = COPMA.MA047;
                    command.Parameters.Add("@MA048", SqlDbType.NVarChar).Value = COPMA.MA048;
                    command.Parameters.Add("@MA049", SqlDbType.NVarChar).Value = COPMA.MA049;
                    command.Parameters.Add("@MA050", SqlDbType.NVarChar).Value = COPMA.MA050;
                    command.Parameters.Add("@MA051", SqlDbType.NVarChar).Value = COPMA.MA051;
                    command.Parameters.Add("@MA052", SqlDbType.NVarChar).Value = COPMA.MA052;
                    command.Parameters.Add("@MA053", SqlDbType.NVarChar).Value = COPMA.MA053;
                    command.Parameters.Add("@MA054", SqlDbType.NVarChar).Value = COPMA.MA054;
                    command.Parameters.Add("@MA055", SqlDbType.NVarChar).Value = COPMA.MA055;
                    command.Parameters.Add("@MA056", SqlDbType.NVarChar).Value = COPMA.MA056;
                    command.Parameters.Add("@MA057", SqlDbType.NVarChar).Value = COPMA.MA057;
                    command.Parameters.Add("@MA058", SqlDbType.NVarChar).Value = COPMA.MA058;
                    command.Parameters.Add("@MA059", SqlDbType.NVarChar).Value = COPMA.MA059;
                    command.Parameters.Add("@MA060", SqlDbType.NVarChar).Value = COPMA.MA060;
                    command.Parameters.Add("@MA061", SqlDbType.NVarChar).Value = COPMA.MA061;
                    command.Parameters.Add("@MA062", SqlDbType.NVarChar).Value = COPMA.MA062;
                    command.Parameters.Add("@MA063", SqlDbType.NVarChar).Value = COPMA.MA063;
                    command.Parameters.Add("@MA064", SqlDbType.NVarChar).Value = COPMA.MA064;
                    command.Parameters.Add("@MA065", SqlDbType.NVarChar).Value = COPMA.MA065;
                    command.Parameters.Add("@MA066", SqlDbType.NVarChar).Value = COPMA.MA066;
                    command.Parameters.Add("@MA067", SqlDbType.NVarChar).Value = COPMA.MA067;
                    command.Parameters.Add("@MA068", SqlDbType.NVarChar).Value = COPMA.MA068;
                    command.Parameters.Add("@MA069", SqlDbType.NVarChar).Value = COPMA.MA069;
                    command.Parameters.Add("@MA070", SqlDbType.NVarChar).Value = COPMA.MA070;
                    command.Parameters.Add("@MA071", SqlDbType.NVarChar).Value = COPMA.MA071;
                    command.Parameters.Add("@MA072", SqlDbType.NVarChar).Value = COPMA.MA072;
                    command.Parameters.Add("@MA073", SqlDbType.NVarChar).Value = COPMA.MA073;
                    command.Parameters.Add("@MA074", SqlDbType.NVarChar).Value = COPMA.MA074;
                    command.Parameters.Add("@MA075", SqlDbType.NVarChar).Value = COPMA.MA075;
                    command.Parameters.Add("@MA076", SqlDbType.NVarChar).Value = COPMA.MA076;
                    command.Parameters.Add("@MA077", SqlDbType.NVarChar).Value = COPMA.MA077;
                    command.Parameters.Add("@MA078", SqlDbType.NVarChar).Value = COPMA.MA078;
                    command.Parameters.Add("@MA079", SqlDbType.NVarChar).Value = COPMA.MA079;
                    command.Parameters.Add("@MA080", SqlDbType.NVarChar).Value = COPMA.MA080;
                    command.Parameters.Add("@MA081", SqlDbType.NVarChar).Value = COPMA.MA081;
                    command.Parameters.Add("@MA082", SqlDbType.NVarChar).Value = COPMA.MA082;
                    command.Parameters.Add("@MA083", SqlDbType.NVarChar).Value = COPMA.MA083;
                    command.Parameters.Add("@MA084", SqlDbType.NVarChar).Value = COPMA.MA084;
                    command.Parameters.Add("@MA085", SqlDbType.NVarChar).Value = COPMA.MA085;
                    command.Parameters.Add("@MA086", SqlDbType.NVarChar).Value = COPMA.MA086;
                    command.Parameters.Add("@MA087", SqlDbType.NVarChar).Value = COPMA.MA087;
                    command.Parameters.Add("@MA088", SqlDbType.NVarChar).Value = COPMA.MA088;
                    command.Parameters.Add("@MA089", SqlDbType.NVarChar).Value = COPMA.MA089;
                    command.Parameters.Add("@MA090", SqlDbType.NVarChar).Value = COPMA.MA090;
                    command.Parameters.Add("@MA091", SqlDbType.NVarChar).Value = COPMA.MA091;
                    command.Parameters.Add("@MA092", SqlDbType.NVarChar).Value = COPMA.MA092;
                    command.Parameters.Add("@MA093", SqlDbType.NVarChar).Value = COPMA.MA093;
                    command.Parameters.Add("@MA094", SqlDbType.NVarChar).Value = COPMA.MA094;
                    command.Parameters.Add("@MA095", SqlDbType.NVarChar).Value = COPMA.MA095;
                    command.Parameters.Add("@MA096", SqlDbType.NVarChar).Value = COPMA.MA096;
                    command.Parameters.Add("@MA097", SqlDbType.NVarChar).Value = COPMA.MA097;
                    command.Parameters.Add("@MA098", SqlDbType.NVarChar).Value = COPMA.MA098;
                    command.Parameters.Add("@MA099", SqlDbType.NVarChar).Value = COPMA.MA099;
                    command.Parameters.Add("@MA100", SqlDbType.NVarChar).Value = COPMA.MA100;
                    command.Parameters.Add("@MA101", SqlDbType.NVarChar).Value = COPMA.MA101;
                    command.Parameters.Add("@MA102", SqlDbType.NVarChar).Value = COPMA.MA102;
                    command.Parameters.Add("@MA103", SqlDbType.NVarChar).Value = COPMA.MA103;
                    command.Parameters.Add("@MA104", SqlDbType.NVarChar).Value = COPMA.MA104;
                    command.Parameters.Add("@MA105", SqlDbType.NVarChar).Value = COPMA.MA105;
                    command.Parameters.Add("@MA106", SqlDbType.NVarChar).Value = COPMA.MA106;
                    command.Parameters.Add("@MA107", SqlDbType.NVarChar).Value = COPMA.MA107;
                    command.Parameters.Add("@MA108", SqlDbType.NVarChar).Value = COPMA.MA108;
                    command.Parameters.Add("@MA109", SqlDbType.NVarChar).Value = COPMA.MA109;
                    command.Parameters.Add("@MA110", SqlDbType.NVarChar).Value = COPMA.MA110;
                    command.Parameters.Add("@MA111", SqlDbType.NVarChar).Value = COPMA.MA111;
                    command.Parameters.Add("@MA112", SqlDbType.NVarChar).Value = COPMA.MA112;
                    command.Parameters.Add("@MA113", SqlDbType.NVarChar).Value = COPMA.MA113;
                    command.Parameters.Add("@MA114", SqlDbType.NVarChar).Value = COPMA.MA114;
                    command.Parameters.Add("@MA115", SqlDbType.NVarChar).Value = COPMA.MA115;
                    command.Parameters.Add("@MA116", SqlDbType.NVarChar).Value = COPMA.MA116;
                    command.Parameters.Add("@MA117", SqlDbType.NVarChar).Value = COPMA.MA117;
                    command.Parameters.Add("@MA118", SqlDbType.NVarChar).Value = COPMA.MA118;
                    command.Parameters.Add("@MA119", SqlDbType.NVarChar).Value = COPMA.MA119;
                    command.Parameters.Add("@MA120", SqlDbType.NVarChar).Value = COPMA.MA120;
                    command.Parameters.Add("@MA121", SqlDbType.NVarChar).Value = COPMA.MA121;
                    command.Parameters.Add("@MA122", SqlDbType.NVarChar).Value = COPMA.MA122;
                    command.Parameters.Add("@MA123", SqlDbType.NVarChar).Value = COPMA.MA123;
                    command.Parameters.Add("@MA124", SqlDbType.NVarChar).Value = COPMA.MA124;
                    command.Parameters.Add("@MA125", SqlDbType.NVarChar).Value = COPMA.MA125;
                    command.Parameters.Add("@MA126", SqlDbType.NVarChar).Value = COPMA.MA126;
                    command.Parameters.Add("@MA127", SqlDbType.NVarChar).Value = COPMA.MA127;
                    command.Parameters.Add("@MA128", SqlDbType.NVarChar).Value = COPMA.MA128;
                    command.Parameters.Add("@MA129", SqlDbType.NVarChar).Value = COPMA.MA129;
                    command.Parameters.Add("@MA130", SqlDbType.NVarChar).Value = COPMA.MA130;
                    command.Parameters.Add("@MA131", SqlDbType.NVarChar).Value = COPMA.MA131;
                    command.Parameters.Add("@MA132", SqlDbType.NVarChar).Value = COPMA.MA132;
                    command.Parameters.Add("@MA133", SqlDbType.NVarChar).Value = COPMA.MA133;
                    command.Parameters.Add("@MA134", SqlDbType.NVarChar).Value = COPMA.MA134;
                    command.Parameters.Add("@MA135", SqlDbType.NVarChar).Value = COPMA.MA135;
                    command.Parameters.Add("@MA136", SqlDbType.NVarChar).Value = COPMA.MA136;
                    command.Parameters.Add("@MA137", SqlDbType.NVarChar).Value = COPMA.MA137;
                    command.Parameters.Add("@MA138", SqlDbType.NVarChar).Value = COPMA.MA138;
                    command.Parameters.Add("@MA139", SqlDbType.NVarChar).Value = COPMA.MA139;
                    command.Parameters.Add("@MA140", SqlDbType.NVarChar).Value = COPMA.MA140;
                    command.Parameters.Add("@MA141", SqlDbType.NVarChar).Value = COPMA.MA141;
                    command.Parameters.Add("@MA142", SqlDbType.NVarChar).Value = COPMA.MA142;
                    command.Parameters.Add("@MA143", SqlDbType.NVarChar).Value = COPMA.MA143;
                    command.Parameters.Add("@MA144", SqlDbType.NVarChar).Value = COPMA.MA144;
                    command.Parameters.Add("@MA145", SqlDbType.NVarChar).Value = COPMA.MA145;
                    command.Parameters.Add("@MA146", SqlDbType.NVarChar).Value = COPMA.MA146;
                    command.Parameters.Add("@MA147", SqlDbType.NVarChar).Value = COPMA.MA147;
                    command.Parameters.Add("@MA148", SqlDbType.NVarChar).Value = COPMA.MA148;
                    command.Parameters.Add("@MA149", SqlDbType.NVarChar).Value = COPMA.MA149;
                    command.Parameters.Add("@MA150", SqlDbType.NVarChar).Value = COPMA.MA150;
                    command.Parameters.Add("@MA151", SqlDbType.NVarChar).Value = COPMA.MA151;
                    command.Parameters.Add("@MA152", SqlDbType.NVarChar).Value = COPMA.MA152;
                    command.Parameters.Add("@MA153", SqlDbType.NVarChar).Value = COPMA.MA153;
                    command.Parameters.Add("@MA154", SqlDbType.NVarChar).Value = COPMA.MA154;
                    command.Parameters.Add("@MA155", SqlDbType.NVarChar).Value = COPMA.MA155;
                    command.Parameters.Add("@MA156", SqlDbType.NVarChar).Value = COPMA.MA156;
                    command.Parameters.Add("@MA157", SqlDbType.NVarChar).Value = COPMA.MA157;
                    command.Parameters.Add("@MA158", SqlDbType.NVarChar).Value = COPMA.MA158;
                    command.Parameters.Add("@MA159", SqlDbType.NVarChar).Value = COPMA.MA159;
                    command.Parameters.Add("@MA160", SqlDbType.NVarChar).Value = COPMA.MA160;
                    command.Parameters.Add("@MA161", SqlDbType.NVarChar).Value = COPMA.MA161;
                    command.Parameters.Add("@MA162", SqlDbType.NVarChar).Value = COPMA.MA162;
                    command.Parameters.Add("@MA163", SqlDbType.NVarChar).Value = COPMA.MA163;
                    command.Parameters.Add("@UDF01", SqlDbType.NVarChar).Value = COPMA.UDF01;
                    command.Parameters.Add("@UDF02", SqlDbType.NVarChar).Value = COPMA.UDF02;
                    command.Parameters.Add("@UDF03", SqlDbType.NVarChar).Value = COPMA.UDF03;
                    command.Parameters.Add("@UDF04", SqlDbType.NVarChar).Value = COPMA.UDF04;
                    command.Parameters.Add("@UDF05", SqlDbType.NVarChar).Value = COPMA.UDF05;
                    command.Parameters.Add("@UDF06", SqlDbType.NVarChar).Value = COPMA.UDF06;
                    command.Parameters.Add("@UDF07", SqlDbType.NVarChar).Value = COPMA.UDF07;
                    command.Parameters.Add("@UDF08", SqlDbType.NVarChar).Value = COPMA.UDF08;
                    command.Parameters.Add("@UDF09", SqlDbType.NVarChar).Value = COPMA.UDF09;
                    command.Parameters.Add("@UDF10", SqlDbType.NVarChar).Value = COPMA.UDF10;


                    command.Connection.Open();

                    int count = command.ExecuteNonQuery();

                    connection.Close();
                    connection.Dispose();

                }
            }
            catch
            {

            }
            finally
            {

            }

        }
    }
}
